# compose.yaml
version: "3.7"

name: orlean-image-generator
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=orleans_image_generator
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./config/db/:/docker-entrypoint-initdb.d/

  silo:
    image: schrodingernft/orlean-image-generator-silohost:hotfix-v1.0.4
    restart: always
    volumes:
      - ./config/silo-appsettings.json:/App/appsettings.json

  webapiclient:
    image: schrodingernft/orlean-image-generator-webapiclient:hotfix-v1.0.4
    restart: always
    volumes:
      - ./config/webapi-appsettings.json:/App/appsettings.json

  watermark:
    image: schrodingernft/watermark-generator
    restart: always
    volumes:
      - ./config/watermark-appsettings.json:/app/appsettings.json

  nginx:
    image: nginx
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
      
