# compose.yaml
version: "3.7"

name: orlean-image-generator
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=orleans_image_generator
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db:/var/lib/mysql

  silo:
    image: dogforever442/orlean-image-generator-silohost
    volumes:
      - ./silo-appsettings.json:/App/appsettings.json

  webapiclient:
    image: dogforever442/orlean-image-generator-webapiclient
    volumes:
      - ./webapi-appsettings.json:/App/appsettings.json

  watermark:
    image: dogforever442/watermark-generator
    volumes:
      - ./watermark-appsettings.json:/app/appsettings.json

  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      
