services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_USER=root
      - MONGO_PASSWORD=password
    command: ["--bind_ip", "0.0.0.0"]
  silo:
    image: schrodingernft/orlean-image-generator-silohost
    restart: always
    volumes:
      - ./config/silo-appsettings.json/:/App/appsettings.json
  webapiclient:
    image: schrodingernft/orlean-image-generator-webapiclient
    restart: always
    volumes:
      - ./config/webapi-appsettings.json/:/App/appsettings.json
    environment:
      - ASPNETCORE_URLS=http://*:5000
  watermark:
    image: schrodingernft/watermark-generator
    restart: always
    environment:
      - ASPNETCORE_URLS=http://*:5050
  nginx:
    image: nginx
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf